import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


public class EposCSVParser {
	private static Pattern datePattern = Pattern.compile("([0-9]{4})年([0-9]{1,2})月([0-9]{1,2})日");
	private static String startMark = "種別";
	private List<TransactionEntry> entries = new LinkedList<TransactionEntry>();

	/**
	 * Parse CSV files generated by Epos Web service.
	 * 
	 * @param args parameters for specifying target CSV files.
	 * @see <a href="https://www.eposcard.co.jp/member/">EPOS Net</a>
	 */
	public static void main(String[] args) {

		// Show help?
		if (args.length < 1 || args.length > 2) {
			String cmd = "java -cp \"bin\" EposCSVParser";
			System.out.println("Usage:");
			System.out.print(cmd); System.out.println(" filepath");
			System.out.print(cmd); System.out.println(" dirpath");
			System.out.print(cmd); System.out.println(" fiscal-year dirpath");
			return;
		}

		// Get parameters.
		String fileName = null;
		String format = "";
		int year = Calendar.getInstance().get(Calendar.YEAR);
		if (args.length == 1) {
			if (new File(args[0]).isFile()) {
				fileName = args[0];
			} else {
				format = Utils.getDirPath(args[0]);
			}
		} else {
			year = Integer.valueOf(args[0]);
			format = Utils.getDirPath(args[1]);
		}

		EposCSVParser parser = new EposCSVParser();
		if (fileName != null) {

			// Parse a CSV file.
			parser.parse(fileName);
			for (TransactionEntry e : parser.getResults()) {
				System.out.println(e.toString());
			}
		} else {

			// Parse CSV files.
			format += "%04d%02d.csv";
			for (int m = 0; m < 12; m ++) {
				int month = m + 3;
				parser.parse(String.format(format, (month / 12) + year, (month % 12) + 1));
				for (TransactionEntry e : parser.getResults()) {
					System.out.println(e.toString());
				}
			}
		}
	}

	public EposCSVParser() {
	}

	public List<TransactionEntry> getResults() {
		return entries;
	}

	public void parse(String fileName) {
		entries.clear();

		BufferedReader reader;
		try {
			reader = new BufferedReader(
					new InputStreamReader(
							new FileInputStream(fileName), "Windows-31J"));
		} catch (FileNotFoundException | UnsupportedEncodingException e) {
			System.err.println(e.getMessage());
			return;
		}

		try {
			String line;
			boolean isEntry = false;
			while ((line = reader.readLine()) != null) {
				if (line.contains(startMark)) {
					isEntry = true;
					continue;
				}
				if (!isEntry) continue;

				// Split CSV items.
				String[] items = line.split(",");
				if (items.length <= 5) continue;

				// Create a new entry instance.
				TransactionEntry entry = new TransactionEntry();
				entries.add(entry);

				// Get transaction date.
				String dateString = Utils.trim(items[1]);
				Matcher matcher = datePattern.matcher(dateString);
				matcher.matches();
				entry.calendar = Calendar.getInstance();
				int year = Integer.valueOf(matcher.group(1));
				int month = Integer.valueOf(matcher.group(2)) - 1;
				int day = Integer.valueOf(matcher.group(3));
				entry.calendar.set(year, month, day);

				// Get transaction detail.
				entry.detail = Utils.trim(items[2]);
				if (!"－".equals(items[3])) {
					entry.detail += String.format(" (%s)", items[3]);
				}

				// Get amount
				String amountString = Utils.trim(items[4]);
				entry.amount = Integer.valueOf(amountString);
			}
		} catch (IOException e) {
			System.err.println(e.getMessage());
		} finally {
			try { reader.close(); }
			catch (IOException e) {}
		}
	}

}
